apiVersion: v1
kind: Service
metadata:
  name: management-service
spec:
  selector:
    app: management-service
  ports:
    - protocol: TCP
      port: 8920
      targetPort: 80
      nodePort: 31164
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-deployment
  labels:
    app: management-service
spec:
  selector:
    matchLabels:
      app: management-service
  replicas: 1 # Número deseado de réplicas
  template:
    metadata:
      labels:
        app: management-service
    spec:
      containers:
      - name: management-service-container
        image: dubansgupc/management_api:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: MONGO_CONNECTION_STRING
          value: "mongodb://dubancsierra:4eLNFkI9TFCLgYzP@$(SERVICIO2_NOMBRE)/test?directConnection=true&authSource=admin&appName=mongosh+2.1.5"
