apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway-container
        image: dubansgupc/note_manage_api_gateway:1.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /app/appsettings.json
          name: appsettings-volume-json
      volumes:
      - name: appsettings-volume
        hostPath:
      - name: appsettings-volume-json
        hostPath:
          path: /home/ubuntu/settings/appsettings.json
          type: FileOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8080
      nodePort: 31163
  type: NodePort
