apiVersion: v1
kind: PersistentVolume
metadata:
  name: appsettings-pv
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /settings/apigateway/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appsettings-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway-container
        image: dubansgupc/note_manage_api_gateway:lastest  
        ports:
        - containerPort: 80
        volumeMounts:
        - name: appsettings-volume
          mountPath: /src/ApiGateway.Api/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: appsettings-volume
        persistentVolumeClaim:
          claimName: appsettings-pvc  # Referencia al PVC creado anteriormente

---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 80
      nodePort: 31163
  type: NodePort
