apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 9812
      targetPort: 9812
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1 # Número deseado de réplicas
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: dubansgupc/authapi_quick_dispath:latest
        ports:
        - containerPort: 9812
        env:
        - name: ACCESS_KEY
          value: ""
        - name: CLIENT_ID
          value: ""
        - name: CLIENT_SECRET
          value: ""
        - name: SECRET_KEY
          value: ""
