apiVersion: v1
kind: Service
metadata:
  name: back-end-notes
spec:
  selector:
    app: back-end-notes
  ports:
    - protocol: TCP
      port: 8920
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-end-notes
  template:
    metadata:
      labels:
        app: back-end-notes
    spec:
      containers:
        - name: back-end
          image: dubansgupc/note_manage_api:latest
          ports:
            - containerPort: 80
          env:
            - name: password_data_base
              value: "4eLNFkI9TFCLgYzP"
            - name: user_data_base
              value: "dubancsierra"
            - name: server_ip_data_base
              value: "mongodb"
            - name: appname_data_base
              value: "test"
            - name: server_port_data_base
              value: "27017"
      hostname: back-end-notes
